### ISSUE TITLE
Unable to find this plugin in Android studio 

### ISSUE THREAD

**Issue by lupin-de-mid** [DmitryZhelnin/git-extensions-intellij#1]
Version of android studio 

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by DmitryZhelnin** [comment]
Plugin version with latest Android Studio support has been published. Please, check its availability and report back.

**Comment by lupin-de-mid** [comment]
After update of AS to
Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Still not found in plugins repository

**Comment by DmitryZhelnin** [comment]
@lupin-de-mid New update has been approved. Can you check one more time?

**Comment by lupin-de-mid** [comment]
Checked
Ok!
